-- Create the products table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price INTEGER NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL,
  colors TEXT[] DEFAULT '{}',
  sizes TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Allow public read access to products
CREATE POLICY "Public profiles are viewable by everyone."
  ON public.products FOR SELECT
  USING ( true );

-- Seed some initial data matching our frontend layout
INSERT INTO public.products (id, name, description, price, category, image_url, colors, sizes)
VALUES
  (1, 'Minimalist Leather Tote', 'Handcrafted from full-grain Italian leather, this minimalist tote is designed for the modern woman. Its spacious interior easily fits a 15-inch laptop and daily essentials, while the structured silhouette maintains an effortlessly elegant profile.', 14500, 'Women''s Accessories', 'https://images.unsplash.com/photo-1591561954557-26941169b49e?q=80&w=1200', ARRAY['#D2B48C', '#111111'], ARRAY['One Size']),
  (2, 'Sculptural Ceramic Vase', 'Handcrafted by artisans, this minimalist ceramic vase brings an earthy, grounding element to any living space. Its irregular, sculptural form is designed to look beautiful both as a standalone art piece or filled with your favorite dried botanicals.', 4200, 'Home Accessories', 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200', ARRAY['#FAFAFA', '#333333'], ARRAY['Standard']),
  (3, 'Oversized Sunglasses', 'Make a statement with these vintage-inspired oversized sunglasses. Featuring premium polarized lenses for ultimate UV protection and lightweight acetate frames for all-day comfort.', 6800, 'Women''s Accessories', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1200', ARRAY['#111111', '#8B4513'], ARRAY['Standard']),
  (4, 'Brass Table Lamp', 'Illuminate your desk or nightstand with this sleek brass table lamp. Merging vintage industrial charm with modern minimalism, it features an adjustable shade and a weighted base for ultimate stability and targeted lighting.', 9950, 'Lighting', 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1200', ARRAY['#D4AF37', '#111111'], ARRAY['One Size']);
